linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  goimports:
    local-prefixes: blue-banner-engine
  golint:
    min-confidence: 0.8

linters:
  enable:
    - gofmt
    - goimports
    - golint
    - vet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - gocyclo
    - misspell

issues:
  exclude-use-default: false
  exclude:
    - "should have a package comment"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
