FROM python:3.13-slim

WORKDIR /app


RUN addgroup --system app && adduser --system --group app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./matchpoint /app/matchpoint
COPY ./models /app/models
COPY ./matchpoint/data /app/matchpoint/data

RUN chown -R app:app /app

USER app

EXPOSE 50051

CMD ["python", "-m", "matchpoint.server"]