services:
  
  go-api:
    build:
      context: .
      dockerfile: Dockerfile.go
    container_name: go-api-server
    ports:
      - "8080:8080" 
    environment:
      - TBA_API_KEY=${TBA_API_KEY} 
      - GRPC_SERVER_ADDRESS=python-predictor:50051
    volumes:
      - .env:/.env
    networks:
      - bbe-net
    depends_on:
      - python-predictor 

  
  python-predictor:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-predictor-service
    environment:
      
      - TBA_API_KEY=${TBA_API_KEY} 
      - TESTING=false
      
    env_file:
      - .env 
    networks:
      - bbe-net
    
    

networks:
  bbe-net:
    driver: bridge