basePath: /api/v1
definitions:
  routes.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  routes.TbaEvent:
    properties:
      city:
        type: string
      country:
        type: string
      end_date:
        type: string
      event_code:
        type: string
      event_type:
        type: integer
      key:
        type: string
      name:
        type: string
      start_date:
        type: string
      state_prov:
        type: string
    type: object
  types.MatchPrediction:
    properties:
      actual_scores:
        additionalProperties:
          type: integer
        example:
          blue: 98
          red: 100
        type: object
      actual_winner:
        example: red
        type: string
      match_key:
        example: 2025mxle_qm1
        type: string
      predicted_scores:
        additionalProperties:
          type: integer
        example:
          blue: 112
          red: 95
        type: object
      predicted_winner:
        example: blue
        type: string
      shap_analysis:
        $ref: '#/definitions/types.ShapAnalysis'
      status:
        example: played
        type: string
      win_probability:
        additionalProperties:
          type: number
        example:
          blue: 0.79
          red: 0.21
        type: object
    type: object
  types.ShapAnalysis:
    properties:
      base_value:
        type: number
      feature_data:
        items:
          type: number
        type: array
      feature_names:
        items:
          type: string
        type: array
      values:
        items:
          type: number
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API server for the Blue Banner Engine, providing FRC match
    predictions.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Blue Banner Engine (BBE) API
  version: "1.0"
paths:
  /events/{year}:
    get:
      description: Retrieves a simplified list of all FRC events for a given year
        from The Blue Alliance.
      parameters:
      - description: FRC Year (e.g., 2024)
        in: path
        name: year
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.TbaEvent'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.ErrorResponse'
      summary: Get All Events for a Year
      tags:
      - events
  /predict/event/{event_key}:
    get:
      consumes:
      - application/json
      description: Retrieves all match predictions for a given FRC event key from
        the BBE prediction service.
      parameters:
      - description: FRC Event Key (e.g., 2025mxle)
        in: path
        name: event_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful prediction for all matches
          schema:
            items:
              $ref: '#/definitions/types.MatchPrediction'
            type: array
        "500":
          description: Internal Server Error (e.g., gRPC call failed)
          schema:
            $ref: '#/definitions/routes.ErrorResponse'
      summary: Get All Match Predictions for an Event
      tags:
      - predictions
  /predict/match/{match_key}:
    get:
      consumes:
      - application/json
      description: Retrieves a detailed prediction for a single FRC match, including
        SHAP analysis for model explainability.
      parameters:
      - description: FRC Match Key (e.g., 2025mxle_qm12)
        in: path
        name: match_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful prediction
          schema:
            $ref: '#/definitions/types.MatchPrediction'
        "500":
          description: Internal Server Error (e.g., gRPC call failed)
          schema:
            $ref: '#/definitions/routes.ErrorResponse'
      summary: Get Single Match Prediction with SHAP
      tags:
      - predictions
swagger: "2.0"
